[2025-04-13 18:38:51,386] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: transform_and_load.wait_for_power_plant_data scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13 18:38:51,394] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: transform_and_load.wait_for_power_plant_data scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13 18:38:51,394] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-04-13 18:38:51,395] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2025-04-13 18:38:51,395] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-04-13 18:38:51,404] {taskinstance.py:1259} INFO - Executing <Task(ExternalTaskSensor): wait_for_power_plant_data> on 2025-04-12 00:00:00+00:00
[2025-04-13 18:38:51,411] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'transform_and_load', 'wait_for_power_plant_data', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '1361', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_transform.py', '--cfg-path', '/tmp/tmp48455w0a', '--error-file', '/tmp/tmpt0or8oim']
[2025-04-13 18:38:51,408] {standard_task_runner.py:52} INFO - Started process 489 to run task
[2025-04-13 18:38:51,413] {standard_task_runner.py:77} INFO - Job 1361: Subtask wait_for_power_plant_data
[2025-04-13 18:38:51,461] {logging_mixin.py:109} INFO - Running <TaskInstance: transform_and_load.wait_for_power_plant_data scheduled__2025-04-12T00:00:00+00:00 [running]> on host 502d6bc01544
[2025-04-13 18:38:51,502] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=transform_and_load
AIRFLOW_CTX_TASK_ID=wait_for_power_plant_data
AIRFLOW_CTX_EXECUTION_DATE=2025-04-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-04-12T00:00:00+00:00
[2025-04-13 18:38:51,508] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-04-13 18:38:51,509] {external_task.py:173} INFO - Poking for tasks ['final_cleanup'] in dag power_plant_data on 2025-04-12T00:00:00+00:00 ... 
[2025-04-13 18:38:51,519] {base.py:249} INFO - Success criteria met. Exiting.
[2025-04-13 18:38:51,528] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=transform_and_load, task_id=wait_for_power_plant_data, execution_date=20250412T000000, start_date=20250413T183851, end_date=20250413T183851
[2025-04-13 18:38:51,547] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-04-13 18:38:51,572] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
